\c cs415

--#1 WebUser
CREATE TABLE WebUser (
  web_user_id INT GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(25) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  email VARCHAR(40)  UNIQUE NOT NULL,
  password VARCHAR(40) NOT NULL,
  created_date TIMESTAMP DEFAULT NULL,
  is_active BOOLEAN DEFAULT true,
  last_login TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (web_user_id)
);

--#2 AddressType
CREATE TABLE AddressType (
    address_type_id INT GENERATED BY DEFAULT AS IDENTITY,
    address_type VARCHAR(20) NOT NULL,
    PRIMARY KEY (address_type_id)
);

--#3 PhoneType
CREATE TABLE PhoneType (
    phone_type_id INT GENERATED BY DEFAULT AS IDENTITY,
    phone_type VARCHAR(10) NOT NULL,
    PRIMARY KEY (phone_type_id)
);

--#4 UserAddress
CREATE TABLE UserAddress (
    user_address_id INT GENERATED BY DEFAULT AS IDENTITY,
    web_user_id INT NOT NULL,
    street_1 VARCHAR(50),
    street_2 VARCHAR(50),
    city VARCHAR(35),
    st VARCHAR(2),
    zip VARCHAR(10),
    country VARCHAR(30),
    created_date TIMESTAMP,
    address_type_id INT NOT NULL,
    PRIMARY KEY (user_address_id),
    FOREIGN KEY (web_user_id ) REFERENCES WebUser(web_user_id )
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (address_type_id) REFERENCES AddressType(address_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

--#5 UserPhone
CREATE TABLE UserPhone (
    user_phone_id INT GENERATED BY DEFAULT AS IDENTITY,
    phone_type_id INT NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    created_date TIMESTAMP,
    is_active BOOLEAN DEFAULT false,
    web_user_id INT NOT NULL,
    primary key (user_phone_id),
    FOREIGN KEY (web_user_id ) REFERENCES WebUser(web_user_id )
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (phone_type_id) REFERENCES PhoneType(phone_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

--#6 UserInfo
CREATE TABLE UserInfo (
    user_info_id INT GENERATED BY DEFAULT AS IDENTITY,
    web_user_id INT NOT NULL,
    profile_bio VARCHAR(500),
    profile_image_url VARCHAR(150),
    modified_date TIMESTAMP,
    created_date TIMESTAMP,
    PRIMARY KEY (user_info_id),
    FOREIGN KEY (web_user_id) REFERENCES WebUser(web_user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

--#7 PageData
CREATE TABLE PageData (
    page_data_id INT GENERATED BY DEFAULT AS IDENTITY,
    page_name VARCHAR(150) NOT NULL,
    page_title VARCHAR(150) NOT NULL,
    page_description TEXT NOT NULL,
    page_picture VARCHAR(250) NOT NULL,
    page_menu VARCHAR(50) NOT NULL,
    PRIMARY KEY (page_data_id)
);